Creation an OWL/TTL file for data model for wikkulpl
ontohgis/wikikul pull request #17
Opened 2024-02-21 12:25 UTC by bszady

I have added new file in OWL/TTL format to register data model for wikikul

2024-02-21 17:54 UTC, przemekgradzki requested changes

2024-02-21 17:54 UTC, przemekgradzki commented on Data Model/ontowikikul.ttl
> +@prefix : <http://www.semanticweb.org/histo/ontologies/2024/1/untitled-ontology-39/> .
```suggestion
@prefix : <https://onto.kul.pl/ontowikikul/> .
@prefix ontowikikul: <https://onto.kul.pl/ontowikikul/> .
```

2024-02-21 17:54 UTC, przemekgradzki commented on Data Model/ontowikikul.ttl
> +@base <http://www.semanticweb.org/histo/ontologies/2024/1/untitled-ontology-39/> .
```suggestion
@base <https://onto.kul.pl/ontowikikul/> .
```

2024-02-23 10:13 UTC, bszady commented
@przemekgradzki @bernardyn I think it is ready, please accept. Further work in the next pull request

2024-02-23 10:26 UTC, bernardyn approved these changes, later dismissed
looks fine

2024-02-23 13:03 UTC, przemekgradzki approved these changes
OK after applying  serialization (7aa24eb)

2024-02-23 13:34 UTC, bernardyn approved these changes
serialisation always :) approve

2024-02-23 13:36 UTC, merged