Settings for "Wikidata:External identifiers"
ontohgis/wikikul pull request #22
Opened 2024-02-23 14:59 UTC by przemekgradzki

Closes #21

2024-02-23 15:02 UTC, bszady submitted a review, later dismissed

2024-02-23 15:43 UTC, bernardyn requested changes

2024-02-23 15:43 UTC, bernardyn commented on Data Model/mainProperties.js
> +            id:  'P12',
in my opinion it should be null now - because this property is not created in wiki yet

2024-02-23 15:43 UTC, bernardyn commented on Data Model/mainProperties.js
> +            id:  'P13',
also null now

2024-02-23 15:43 UTC, bernardyn commented on Data Model/mainProperties.js
> +                    'https://onto.kul.pl/ontohgis/$1',
claim should be added after properties will be created

2024-02-26 10:47 UTC, przemekgradzki commented on Data Model/mainProperties.js
> +            id:  'P12',
Completely reworked

2024-02-27 09:14 UTC, bszady approved these changes

2024-02-28 20:26 UTC, bernardyn approved these changes

2024-02-28 20:26 UTC, merged