Lhdb 821 missing p
ontohgis/wikikul pull request #24
Opened 2024-04-21 02:38 UTC by bernardyn

2024-04-23 05:46 UTC, bszady commented on Data Model/contribution1561.js
Should be "opodatkowany od", in english: "taxed on"

2024-04-23 05:47 UTC, bszady commented on Data Model/contribution1561.js
> +                pl: 'podatnik',
opodatkowany od

2024-04-23 05:48 UTC, bszady commented on Data Model/contribution1561.js
> +                pl: 'podatnik',
taxed on

2024-04-23 05:49 UTC, bszady commented on Data Model/contribution1561.js
> +                en: null
en: taxed on

2024-04-23 05:51 UTC, bszady requested changes
Should be "opodatkowany od", in english: "taxed on"

2024-04-23 05:52 UTC, bszady approved these changes, later dismissed

2024-04-25 13:28 UTC, bernardyn commented on Data Model/contribution1561.js
> +                pl: 'podatnik',
podatek od

2024-04-25 13:29 UTC, bernardyn commented on Data Model/contribution1561.js
> +                en: null
empty

2024-04-25 14:15 UTC, bernardyn commented
@bszady definitely we need english labels

2024-04-28 10:01 UTC, bszady approved these changes

2026-04-26 20:27 UTC, lpoznanski commented
Already added. No longer relevant.

2026-04-26 20:27 UTC, closed without merging