Add first property
ontohgis/wikikul pull request #25
Opened 2024-05-27 09:57 UTC by bernardyn

2024-05-27 20:48 UTC, bszady approved these changes

2024-05-31 09:49 UTC, bernardyn commented
@przemekgradzki please take a look

2024-06-07 21:35 UTC, przemekgradzki requested changes

2024-06-07 21:35 UTC, przemekgradzki commented on DataModel/ontowikikul.ttl
> +		"deanery (Latin Church)"@en ,
Why _deanery_ is _owl:AnnotationProperty_??
See e.g. [ontohgis/administrative_type_150](https://onto.kul.pl/ontohgis/administrative_type_150.ttl):
```
ontohgis:administrative_type_150
        a                               owl:Class ;
        rdfs:label                      "decanatus"@la , "dekanat (Kościół katolicki ob. łacińskiego)"@pl , "deanery (Latin Church)"@en ;
```

2026-04-26 20:28 UTC, lpoznanski commented
No longer relevant

2026-04-26 20:28 UTC, closed without merging